# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hxxie/forward_star/Spruce

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hxxie/forward_star/Spruce

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hxxie/forward_star/Spruce/CMakeFiles /home/hxxie/forward_star/Spruce//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hxxie/forward_star/Spruce/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named spruce

# Build rule for target.
spruce: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spruce
.PHONY : spruce

# fast build rule for target.
spruce/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spruce.dir/build.make CMakeFiles/spruce.dir/build
.PHONY : spruce/fast

#=============================================================================
# Target rules for targets named Spruce

# Build rule for target.
Spruce: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Spruce
.PHONY : Spruce

# fast build rule for target.
Spruce/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spruce.dir/build.make CMakeFiles/Spruce.dir/build
.PHONY : Spruce/fast

#=============================================================================
# Target rules for targets named junction

# Build rule for target.
junction: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 junction
.PHONY : junction

# fast build rule for target.
junction/fast:
	$(MAKE) $(MAKESILENT) -f junction/CMakeFiles/junction.dir/build.make junction/CMakeFiles/junction.dir/build
.PHONY : junction/fast

#=============================================================================
# Target rules for targets named turf

# Build rule for target.
turf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 turf
.PHONY : turf

# fast build rule for target.
turf/fast:
	$(MAKE) $(MAKESILENT) -f junction/turf/CMakeFiles/turf.dir/build.make junction/turf/CMakeFiles/turf.dir/build
.PHONY : turf/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spruce.dir/build.make CMakeFiles/Spruce.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spruce.dir/build.make CMakeFiles/Spruce.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spruce.dir/build.make CMakeFiles/Spruce.dir/main.cpp.s
.PHONY : main.cpp.s

src/index_algorithms.o: src/index_algorithms.cpp.o
.PHONY : src/index_algorithms.o

# target to build an object file
src/index_algorithms.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spruce.dir/build.make CMakeFiles/spruce.dir/src/index_algorithms.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spruce.dir/build.make CMakeFiles/Spruce.dir/src/index_algorithms.cpp.o
.PHONY : src/index_algorithms.cpp.o

src/index_algorithms.i: src/index_algorithms.cpp.i
.PHONY : src/index_algorithms.i

# target to preprocess a source file
src/index_algorithms.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spruce.dir/build.make CMakeFiles/spruce.dir/src/index_algorithms.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spruce.dir/build.make CMakeFiles/Spruce.dir/src/index_algorithms.cpp.i
.PHONY : src/index_algorithms.cpp.i

src/index_algorithms.s: src/index_algorithms.cpp.s
.PHONY : src/index_algorithms.s

# target to generate assembly for a file
src/index_algorithms.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spruce.dir/build.make CMakeFiles/spruce.dir/src/index_algorithms.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spruce.dir/build.make CMakeFiles/Spruce.dir/src/index_algorithms.cpp.s
.PHONY : src/index_algorithms.cpp.s

src/memory_analysis.o: src/memory_analysis.cpp.o
.PHONY : src/memory_analysis.o

# target to build an object file
src/memory_analysis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spruce.dir/build.make CMakeFiles/spruce.dir/src/memory_analysis.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spruce.dir/build.make CMakeFiles/Spruce.dir/src/memory_analysis.cpp.o
.PHONY : src/memory_analysis.cpp.o

src/memory_analysis.i: src/memory_analysis.cpp.i
.PHONY : src/memory_analysis.i

# target to preprocess a source file
src/memory_analysis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spruce.dir/build.make CMakeFiles/spruce.dir/src/memory_analysis.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spruce.dir/build.make CMakeFiles/Spruce.dir/src/memory_analysis.cpp.i
.PHONY : src/memory_analysis.cpp.i

src/memory_analysis.s: src/memory_analysis.cpp.s
.PHONY : src/memory_analysis.s

# target to generate assembly for a file
src/memory_analysis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spruce.dir/build.make CMakeFiles/spruce.dir/src/memory_analysis.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spruce.dir/build.make CMakeFiles/Spruce.dir/src/memory_analysis.cpp.s
.PHONY : src/memory_analysis.cpp.s

src/spruce_transaction.o: src/spruce_transaction.cpp.o
.PHONY : src/spruce_transaction.o

# target to build an object file
src/spruce_transaction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spruce.dir/build.make CMakeFiles/spruce.dir/src/spruce_transaction.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spruce.dir/build.make CMakeFiles/Spruce.dir/src/spruce_transaction.cpp.o
.PHONY : src/spruce_transaction.cpp.o

src/spruce_transaction.i: src/spruce_transaction.cpp.i
.PHONY : src/spruce_transaction.i

# target to preprocess a source file
src/spruce_transaction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spruce.dir/build.make CMakeFiles/spruce.dir/src/spruce_transaction.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spruce.dir/build.make CMakeFiles/Spruce.dir/src/spruce_transaction.cpp.i
.PHONY : src/spruce_transaction.cpp.i

src/spruce_transaction.s: src/spruce_transaction.cpp.s
.PHONY : src/spruce_transaction.s

# target to generate assembly for a file
src/spruce_transaction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spruce.dir/build.make CMakeFiles/spruce.dir/src/spruce_transaction.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spruce.dir/build.make CMakeFiles/Spruce.dir/src/spruce_transaction.cpp.s
.PHONY : src/spruce_transaction.cpp.s

src/succinct_algorithms.o: src/succinct_algorithms.cpp.o
.PHONY : src/succinct_algorithms.o

# target to build an object file
src/succinct_algorithms.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spruce.dir/build.make CMakeFiles/spruce.dir/src/succinct_algorithms.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spruce.dir/build.make CMakeFiles/Spruce.dir/src/succinct_algorithms.cpp.o
.PHONY : src/succinct_algorithms.cpp.o

src/succinct_algorithms.i: src/succinct_algorithms.cpp.i
.PHONY : src/succinct_algorithms.i

# target to preprocess a source file
src/succinct_algorithms.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spruce.dir/build.make CMakeFiles/spruce.dir/src/succinct_algorithms.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spruce.dir/build.make CMakeFiles/Spruce.dir/src/succinct_algorithms.cpp.i
.PHONY : src/succinct_algorithms.cpp.i

src/succinct_algorithms.s: src/succinct_algorithms.cpp.s
.PHONY : src/succinct_algorithms.s

# target to generate assembly for a file
src/succinct_algorithms.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spruce.dir/build.make CMakeFiles/spruce.dir/src/succinct_algorithms.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spruce.dir/build.make CMakeFiles/Spruce.dir/src/succinct_algorithms.cpp.s
.PHONY : src/succinct_algorithms.cpp.s

test/demo.o: test/demo.cpp.o
.PHONY : test/demo.o

# target to build an object file
test/demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spruce.dir/build.make CMakeFiles/Spruce.dir/test/demo.cpp.o
.PHONY : test/demo.cpp.o

test/demo.i: test/demo.cpp.i
.PHONY : test/demo.i

# target to preprocess a source file
test/demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spruce.dir/build.make CMakeFiles/Spruce.dir/test/demo.cpp.i
.PHONY : test/demo.cpp.i

test/demo.s: test/demo.cpp.s
.PHONY : test/demo.s

# target to generate assembly for a file
test/demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spruce.dir/build.make CMakeFiles/Spruce.dir/test/demo.cpp.s
.PHONY : test/demo.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Spruce"
	@echo "... junction"
	@echo "... spruce"
	@echo "... turf"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/index_algorithms.o"
	@echo "... src/index_algorithms.i"
	@echo "... src/index_algorithms.s"
	@echo "... src/memory_analysis.o"
	@echo "... src/memory_analysis.i"
	@echo "... src/memory_analysis.s"
	@echo "... src/spruce_transaction.o"
	@echo "... src/spruce_transaction.i"
	@echo "... src/spruce_transaction.s"
	@echo "... src/succinct_algorithms.o"
	@echo "... src/succinct_algorithms.i"
	@echo "... src/succinct_algorithms.s"
	@echo "... test/demo.o"
	@echo "... test/demo.i"
	@echo "... test/demo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

